CREATE TABLE IF NOT EXISTS `#__igallery` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `ordering` int(4) NOT NULL DEFAULT '1',
  `folder` varchar(256) NOT NULL,
  `name` varchar(255) NOT NULL,
  `menu_description` text NOT NULL,
  `gallery_description` text NOT NULL,
  `menu_image_filename` varchar(128) NOT NULL,
  `menu_max_width` int(4) NOT NULL DEFAULT '200',
  `max_width` int(4) NOT NULL DEFAULT '600',
  `max_height` int(4) NOT NULL DEFAULT '400',
  `fade` int(1) NOT NULL DEFAULT '1',
  `preload` int(1) NOT NULL DEFAULT '1',
  `thumb_width` int(4) NOT NULL DEFAULT '90',
  `thumb_height` int(4) NOT NULL DEFAULT '90',
  `thumb_position` varchar(10) NOT NULL DEFAULT 'below',
  `thumb_container_width` int(4) NOT NULL DEFAULT '200',
  `thumb_container_height` int(4) NOT NULL DEFAULT '0',
  `images_per_row` int(4) NOT NULL DEFAULT '0',
  `thumb_padding` int(4) NOT NULL DEFAULT '4',
  `thumb_scrollbar` int(1) NOT NULL DEFAULT '1',
  `scroll_speed` decimal(2,2) NOT NULL DEFAULT '0.07',
  `scroll_boundary` int(4) NOT NULL DEFAULT '200',
  `photo_des_position` varchar(10) NOT NULL DEFAULT 'above',
  `photo_des_width` int(4) NOT NULL DEFAULT '150',
  `photo_des_height` int(4) NOT NULL DEFAULT '40',
  `align` varchar(10) NOT NULL DEFAULT 'left',
  `lightbox` int(1) NOT NULL DEFAULT '1',
  `lbox_max_width` int(4) NOT NULL DEFAULT '800',
  `lbox_max_height` int(4) NOT NULL DEFAULT '600',
  `lbox_fade` int(1) NOT NULL DEFAULT '1',
  `lbox_preload` int(1) NOT NULL DEFAULT '0',
  `lbox_thumb_width` int(4) NOT NULL DEFAULT '90',
  `lbox_thumb_height` int(4) NOT NULL DEFAULT '90',
  `lbox_thumb_position` varchar(12) NOT NULL DEFAULT 'below',
  `lbox_thumb_container_width` int(4) NOT NULL DEFAULT '200',
  `lbox_thumb_container_height` int(4) NOT NULL DEFAULT '0',
  `lbox_images_per_row` int(3) NOT NULL DEFAULT '0',
  `lbox_thumb_padding` int(4) NOT NULL DEFAULT '4',
  `lbox_thumb_scrollbar` int(1) NOT NULL DEFAULT '1',
  `lbox_scroll_speed` decimal(2,2) NOT NULL DEFAULT '0.07',
  `lbox_scroll_boundary` int(4) NOT NULL DEFAULT '200',
  `lbox_photo_des_position` varchar(10) NOT NULL DEFAULT 'below',
  `lbox_photo_des_width` int(4) NOT NULL DEFAULT '200',
  `lbox_photo_des_height` int(4) NOT NULL DEFAULT '40',
  `img_quality` int(4) NOT NULL DEFAULT '60',
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `gallery_des_position` varchar(10) NOT NULL DEFAULT 'below',
  `arrows_up_down` int(1) NOT NULL DEFAULT '0',
  `arrows_left_right` int(1) NOT NULL DEFAULT '0',
  `lbox_arrows_left_right` int(1) NOT NULL DEFAULT '0',
  `lbox_arrows_up_down` int(1) NOT NULL DEFAULT '0',
  `show_cat_menu` int(1) NOT NULL DEFAULT '0',
  `cat_menu_columns` varchar(2) NOT NULL DEFAULT '2',
  `magnify` int(1) NOT NULL DEFAULT '1',
  `menu_access` int(2) NOT NULL DEFAULT '0',
  `access` int(2) NOT NULL DEFAULT '0',
  `allow_comments` int(1) NOT NULL DEFAULT '0',
  `parent` int(7) NOT NULL DEFAULT '0',
  `allow_rating` int(1) NOT NULL DEFAULT '0',
  `lbox_allow_comments` int(1) NOT NULL DEFAULT '0',
  `lbox_allow_rating` int(1) NOT NULL DEFAULT '0',
  `img_container_width` int(4) NOT NULL DEFAULT '0',
  `img_container_height` int(4) NOT NULL DEFAULT '0',
  `lbox_img_container_width` int(4) NOT NULL DEFAULT '0',
  `lbox_img_container_height` int(4) NOT NULL DEFAULT '0',
  `user` int(7) NOT NULL,
  `show_large_image` int(1) NOT NULL DEFAULT '1',
  `show_thumbs` int(1) NOT NULL DEFAULT '1',
  `show_descriptions` int(1) NOT NULL DEFAULT '1',
  `lbox_show_thumbs` int(1) NOT NULL DEFAULT '1',
  `lbox_show_descriptions` int(1) NOT NULL DEFAULT '1',
  `enable_slideshow` int(1) NOT NULL DEFAULT '0',
  `show_slideshow_controls` int(1) NOT NULL DEFAULT '0',
  `slideshow_pause` int(5) NOT NULL DEFAULT '3000',
  `lbox_enable_slideshow` int(1) NOT NULL DEFAULT '0',
  `lbox_show_slideshow_controls` int(1) NOT NULL DEFAULT '0',
  `lbox_slideshow_pause` int(5) NOT NULL DEFAULT '3000',
  `type` int(1) NOT NULL DEFAULT '1',
  `columns` int(2) NOT NULL DEFAULT '3',
  `slideshow_autostart` int(1) NOT NULL DEFAULT '0',
  `lbox_slideshow_autostart` int(1) NOT NULL DEFAULT '0',
  `menu_max_height` int(4) NOT NULL DEFAULT '80',
  `crop_thumbs` int(1) NOT NULL DEFAULT '1',
  `lbox_crop_thumbs` int(1) NOT NULL DEFAULT '1',
  `alias` varchar(256) NOT NULL,
  `style` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `#__igallery_comments` (
  `id` int(7) NOT NULL AUTO_INCREMENT,
  `img_id` int(7) NOT NULL,
  `text` text NOT NULL,
  `ip` varchar(24) NOT NULL,
  `published` int(1) NOT NULL DEFAULT '1',
  `date` int(11) NOT NULL,
  `author` varchar(64) NOT NULL,
  `gallery_id` int(7) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `#__igallery_img` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `gallery_id` int(5) NOT NULL,
  `filename` varchar(128) NOT NULL,
  `description` text NOT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '1',
  `ordering` int(5) NOT NULL DEFAULT '1',
  `lightbox_width` int(5) NOT NULL,
  `lightbox_height` int(5) NOT NULL,
  `width` int(5) NOT NULL,
  `height` int(5) NOT NULL,
  `filesize` int(6) NOT NULL,
  `link` varchar(255) NOT NULL,
  `target_blank` int(1) NOT NULL DEFAULT '1',
  `access` int(2) NOT NULL DEFAULT '0',
  `thumb_width` int(5) NOT NULL,
  `thumb_height` int(5) NOT NULL,
  `lightbox_thumb_width` int(5) NOT NULL,
  `lightbox_thumb_height` int(5) NOT NULL,
  `alt_text` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `gallery_id` (`gallery_id`)
);

CREATE TABLE IF NOT EXISTS `#__igallery_rating` (
  `id` int(7) NOT NULL AUTO_INCREMENT,
  `img_id` int(7) NOT NULL,
  `rating` int(1) NOT NULL,
  `ip` varchar(24) NOT NULL,
  `date` int(11) NOT NULL DEFAULT '0',
  `author` varchar(64) NOT NULL,
  `published` int(1) NOT NULL DEFAULT '1',
  `gallery_id` int(7) NOT NULL,
  PRIMARY KEY (`id`)
);
